project_id: '481017'
base_path: /
base_url: 'https://api.crowdin.com'
files:
  - source: /permissionsui/src/main/res/values/strings.xml
    translation: /permissionsui/src/main/res/values-%android_code%/%original_file_name%
    languages_mapping:
      android_code:
        de: de
        ru: ru
