complexity:
  LongParameterList:
    functionThreshold: 8
    ignoreDefaultParameters: true

formatting:
  Indentation:
    active: false
    autoCorrect: true
    indentSize: 4
    continuationIndentSize: 4

style:
  MagicNumber:
    ignorePropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated:
      - 'Preview'

naming:
  VariableNaming:
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'
    # TopLevelPropertyNaming:
    # constantPattern: '[A-Z][A-Za-z0-9]*'
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'